// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Type int32

const (
	Message_GET    Message_Type = 0
	Message_PUT    Message_Type = 1
	Message_DELETE Message_Type = 2
)

// Enum value maps for Message_Type.
var (
	Message_Type_name = map[int32]string{
		0: "GET",
		1: "PUT",
		2: "DELETE",
	}
	Message_Type_value = map[string]int32{
		"GET":    0,
		"PUT":    1,
		"DELETE": 2,
	}
)

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}

func (x Message_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_raft_proto_enumTypes[0].Descriptor()
}

func (Message_Type) Type() protoreflect.EnumType {
	return &file_proto_raft_proto_enumTypes[0]
}

func (x Message_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Type.Descriptor instead.
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{0, 0}
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          Message_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=raftpb.Message_Type" json:"type,omitempty"`
	Key           int32                  `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	Value         *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() Message_Type {
	if x != nil {
		return x.Type
	}
	return Message_GET
}

func (x *Message) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Message) GetValue() *wrapperspb.Int32Value {
	if x != nil {
		return x.Value
	}
	return nil
}

type Null struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Null) Reset() {
	*x = Null{}
	mi := &file_proto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{1}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *LogEntry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type VoteRequestArgs struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CandidateId        int32                  `protobuf:"varint,1,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	CandidateTerm      int32                  `protobuf:"varint,2,opt,name=candidateTerm,proto3" json:"candidateTerm,omitempty"`
	CandidateLogLength int32                  `protobuf:"varint,3,opt,name=candidateLogLength,proto3" json:"candidateLogLength,omitempty"`
	CandidateLogTerm   int32                  `protobuf:"varint,4,opt,name=candidateLogTerm,proto3" json:"candidateLogTerm,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VoteRequestArgs) Reset() {
	*x = VoteRequestArgs{}
	mi := &file_proto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequestArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequestArgs) ProtoMessage() {}

func (x *VoteRequestArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequestArgs.ProtoReflect.Descriptor instead.
func (*VoteRequestArgs) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *VoteRequestArgs) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *VoteRequestArgs) GetCandidateTerm() int32 {
	if x != nil {
		return x.CandidateTerm
	}
	return 0
}

func (x *VoteRequestArgs) GetCandidateLogLength() int32 {
	if x != nil {
		return x.CandidateLogLength
	}
	return 0
}

func (x *VoteRequestArgs) GetCandidateLogTerm() int32 {
	if x != nil {
		return x.CandidateLogTerm
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	CurrentTerm   int32                  `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	Granted       bool                   `protobuf:"varint,3,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_proto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{4}
}

func (x *VoteResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *VoteResponse) GetCurrentTerm() int32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *VoteResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type LogRequestArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      int32                  `protobuf:"varint,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	PrefixLen     int32                  `protobuf:"varint,3,opt,name=prefixLen,proto3" json:"prefixLen,omitempty"`
	PrefixTerm    int32                  `protobuf:"varint,4,opt,name=prefixTerm,proto3" json:"prefixTerm,omitempty"`
	CommitLength  int32                  `protobuf:"varint,5,opt,name=commitLength,proto3" json:"commitLength,omitempty"`
	Suffix        []*LogEntry            `protobuf:"bytes,6,rep,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequestArgs) Reset() {
	*x = LogRequestArgs{}
	mi := &file_proto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequestArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequestArgs) ProtoMessage() {}

func (x *LogRequestArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequestArgs.ProtoReflect.Descriptor instead.
func (*LogRequestArgs) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *LogRequestArgs) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *LogRequestArgs) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogRequestArgs) GetPrefixLen() int32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *LogRequestArgs) GetPrefixTerm() int32 {
	if x != nil {
		return x.PrefixTerm
	}
	return 0
}

func (x *LogRequestArgs) GetCommitLength() int32 {
	if x != nil {
		return x.CommitLength
	}
	return 0
}

func (x *LogRequestArgs) GetSuffix() []*LogEntry {
	if x != nil {
		return x.Suffix
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	CurrentTerm   int32                  `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	Ack           int32                  `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use logResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{6}
}

func (x *LogResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *LogResponse) GetCurrentTerm() int32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *LogResponse) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_raft_proto protoreflect.FileDescriptor

const file_proto_raft_proto_rawDesc = "" +
	"\n" +
	"\x10proto/raft.proto\x12\x06raftpb\x1a\x1egoogle/protobuf/wrappers.proto\"\x9e\x01\n" +
	"\aMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.raftpb.Message.TypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\x05R\x03key\x121\n" +
	"\x05value\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05value\"$\n" +
	"\x04Type\x12\a\n" +
	"\x03GET\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\"\x06\n" +
	"\x04Null\"I\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12)\n" +
	"\amessage\x18\x02 \x01(\v2\x0f.raftpb.MessageR\amessage\"\xb5\x01\n" +
	"\x0fVoteRequestArgs\x12 \n" +
	"\vcandidateId\x18\x01 \x01(\x05R\vcandidateId\x12$\n" +
	"\rcandidateTerm\x18\x02 \x01(\x05R\rcandidateTerm\x12.\n" +
	"\x12candidateLogLength\x18\x03 \x01(\x05R\x12candidateLogLength\x12*\n" +
	"\x10candidateLogTerm\x18\x04 \x01(\x05R\x10candidateLogTerm\"b\n" +
	"\fVoteResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x05R\x06nodeId\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\x05R\vcurrentTerm\x12\x18\n" +
	"\agranted\x18\x03 \x01(\bR\agranted\"\xcc\x01\n" +
	"\x0eLogRequestArgs\x12\x1a\n" +
	"\bleaderId\x18\x01 \x01(\x05R\bleaderId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\x1c\n" +
	"\tprefixLen\x18\x03 \x01(\x05R\tprefixLen\x12\x1e\n" +
	"\n" +
	"prefixTerm\x18\x04 \x01(\x05R\n" +
	"prefixTerm\x12\"\n" +
	"\fcommitLength\x18\x05 \x01(\x05R\fcommitLength\x12(\n" +
	"\x06suffix\x18\x06 \x03(\v2\x10.raftpb.LogEntryR\x06suffix\"s\n" +
	"\vLogResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x05R\x06nodeId\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\x05R\vcurrentTerm\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\x05R\x03ack\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess2\xa9\x01\n" +
	"\x04Raft\x12(\n" +
	"\aForward\x12\x0f.raftpb.Message\x1a\f.raftpb.Null\x12<\n" +
	"\vVoteRequest\x12\x17.raftpb.VoteRequestArgs\x1a\x14.raftpb.VoteResponse\x129\n" +
	"\n" +
	"LogRequest\x12\x16.raftpb.LogRequestArgs\x1a\x13.raftpb.LogResponseB=Z;github.com/dominikszczepaniak/distributed-cache/raft/raftpbb\x06proto3"

var (
	file_proto_raft_proto_rawDescOnce sync.Once
	file_proto_raft_proto_rawDescData []byte
)

func file_proto_raft_proto_rawDescGZIP() []byte {
	file_proto_raft_proto_rawDescOnce.Do(func() {
		file_proto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raft_proto_rawDesc), len(file_proto_raft_proto_rawDesc)))
	})
	return file_proto_raft_proto_rawDescData
}

var file_proto_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_raft_proto_goTypes = []any{
	(Message_Type)(0),             // 0: raftpb.Message.Type
	(*Message)(nil),               // 1: raftpb.Message
	(*Null)(nil),                  // 2: raftpb.Null
	(*LogEntry)(nil),              // 3: raftpb.LogEntry
	(*VoteRequestArgs)(nil),       // 4: raftpb.VoteRequestArgs
	(*VoteResponse)(nil),          // 5: raftpb.VoteResponse
	(*LogRequestArgs)(nil),        // 6: raftpb.LogRequestArgs
	(*LogResponse)(nil),           // 7: raftpb.logResponse
	(*wrapperspb.Int32Value)(nil), // 8: google.protobuf.Int32Value
}
var file_proto_raft_proto_depIdxs = []int32{
	0, // 0: raftpb.Message.type:type_name -> raftpb.Message.Type
	8, // 1: raftpb.Message.value:type_name -> google.protobuf.Int32Value
	1, // 2: raftpb.LogEntry.message:type_name -> raftpb.Message
	3, // 3: raftpb.LogRequestArgs.suffix:type_name -> raftpb.LogEntry
	1, // 4: raftpb.Raft.Forward:input_type -> raftpb.Message
	4, // 5: raftpb.Raft.VoteRequest:input_type -> raftpb.VoteRequestArgs
	6, // 6: raftpb.Raft.LogRequest:input_type -> raftpb.LogRequestArgs
	2, // 7: raftpb.Raft.Forward:output_type -> raftpb.Null
	5, // 8: raftpb.Raft.VoteRequest:output_type -> raftpb.VoteResponse
	7, // 9: raftpb.Raft.LogRequest:output_type -> raftpb.logResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_raft_proto_init() }
func file_proto_raft_proto_init() {
	if File_proto_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raft_proto_rawDesc), len(file_proto_raft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_raft_proto_goTypes,
		DependencyIndexes: file_proto_raft_proto_depIdxs,
		EnumInfos:         file_proto_raft_proto_enumTypes,
		MessageInfos:      file_proto_raft_proto_msgTypes,
	}.Build()
	File_proto_raft_proto = out.File
	file_proto_raft_proto_goTypes = nil
	file_proto_raft_proto_depIdxs = nil
}
