// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/raft.proto

package raftpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Message_Type int32

const (
	Message_GET                    Message_Type = 0
	Message_PUT                    Message_Type = 1
	Message_DELETE                 Message_Type = 2
	Message_UPDATE_PARTITION_TABLE Message_Type = 3
)

// Enum value maps for Message_Type.
var (
	Message_Type_name = map[int32]string{
		0: "GET",
		1: "PUT",
		2: "DELETE",
		3: "UPDATE_PARTITION_TABLE",
	}
	Message_Type_value = map[string]int32{
		"GET":                    0,
		"PUT":                    1,
		"DELETE":                 2,
		"UPDATE_PARTITION_TABLE": 3,
	}
)

func (x Message_Type) Enum() *Message_Type {
	p := new(Message_Type)
	*p = x
	return p
}

func (x Message_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_raft_proto_enumTypes[0].Descriptor()
}

func (Message_Type) Type() protoreflect.EnumType {
	return &file_proto_raft_proto_enumTypes[0]
}

func (x Message_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_Type.Descriptor instead.
func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{0, 0}
}

type Message struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Type             Message_Type           `protobuf:"varint,1,opt,name=type,proto3,enum=raftpb.Message_Type" json:"type,omitempty"`
	Key              int32                  `protobuf:"varint,2,opt,name=key,proto3" json:"key,omitempty"`
	Value            *wrapperspb.Int32Value `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	IdempotencyToken string                 `protobuf:"bytes,4,opt,name=idempotency_token,json=idempotencyToken,proto3" json:"idempotency_token,omitempty"`
	ClientId         string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// Partition table update payload (only used when type = UPDATE_PARTITION_TABLE)
	PartitionUpdate *PartitionTableUpdate `protobuf:"bytes,6,opt,name=partition_update,json=partitionUpdate,proto3" json:"partition_update,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_raft_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() Message_Type {
	if x != nil {
		return x.Type
	}
	return Message_GET
}

func (x *Message) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *Message) GetValue() *wrapperspb.Int32Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Message) GetIdempotencyToken() string {
	if x != nil {
		return x.IdempotencyToken
	}
	return ""
}

func (x *Message) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Message) GetPartitionUpdate() *PartitionTableUpdate {
	if x != nil {
		return x.PartitionUpdate
	}
	return nil
}

type Null struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Null) Reset() {
	*x = Null{}
	mi := &file_proto_raft_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Null) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Null) ProtoMessage() {}

func (x *Null) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Null.ProtoReflect.Descriptor instead.
func (*Null) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{1}
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_raft_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequest) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,3,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_raft_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{3}
}

func (x *GetResponse) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *GetResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *GetResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ForwardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ForwardResponse) Reset() {
	*x = ForwardResponse{}
	mi := &file_proto_raft_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ForwardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ForwardResponse) ProtoMessage() {}

func (x *ForwardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ForwardResponse.ProtoReflect.Descriptor instead.
func (*ForwardResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{4}
}

func (x *ForwardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ForwardResponse) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Message       *Message               `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_proto_raft_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{5}
}

func (x *LogEntry) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

type VoteRequestArgs struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CandidateId        int32                  `protobuf:"varint,1,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	CandidateTerm      int32                  `protobuf:"varint,2,opt,name=candidateTerm,proto3" json:"candidateTerm,omitempty"`
	CandidateLogLength int32                  `protobuf:"varint,3,opt,name=candidateLogLength,proto3" json:"candidateLogLength,omitempty"`
	CandidateLogTerm   int32                  `protobuf:"varint,4,opt,name=candidateLogTerm,proto3" json:"candidateLogTerm,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VoteRequestArgs) Reset() {
	*x = VoteRequestArgs{}
	mi := &file_proto_raft_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteRequestArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteRequestArgs) ProtoMessage() {}

func (x *VoteRequestArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteRequestArgs.ProtoReflect.Descriptor instead.
func (*VoteRequestArgs) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{6}
}

func (x *VoteRequestArgs) GetCandidateId() int32 {
	if x != nil {
		return x.CandidateId
	}
	return 0
}

func (x *VoteRequestArgs) GetCandidateTerm() int32 {
	if x != nil {
		return x.CandidateTerm
	}
	return 0
}

func (x *VoteRequestArgs) GetCandidateLogLength() int32 {
	if x != nil {
		return x.CandidateLogLength
	}
	return 0
}

func (x *VoteRequestArgs) GetCandidateLogTerm() int32 {
	if x != nil {
		return x.CandidateLogTerm
	}
	return 0
}

type VoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	CurrentTerm   int32                  `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	Granted       bool                   `protobuf:"varint,3,opt,name=granted,proto3" json:"granted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VoteResponse) Reset() {
	*x = VoteResponse{}
	mi := &file_proto_raft_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoteResponse) ProtoMessage() {}

func (x *VoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoteResponse.ProtoReflect.Descriptor instead.
func (*VoteResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{7}
}

func (x *VoteResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *VoteResponse) GetCurrentTerm() int32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *VoteResponse) GetGranted() bool {
	if x != nil {
		return x.Granted
	}
	return false
}

type LogRequestArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeaderId      int32                  `protobuf:"varint,1,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	Term          int32                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	PrefixLen     int32                  `protobuf:"varint,3,opt,name=prefixLen,proto3" json:"prefixLen,omitempty"`
	PrefixTerm    int32                  `protobuf:"varint,4,opt,name=prefixTerm,proto3" json:"prefixTerm,omitempty"`
	CommitLength  int32                  `protobuf:"varint,5,opt,name=commitLength,proto3" json:"commitLength,omitempty"`
	Suffix        []*LogEntry            `protobuf:"bytes,6,rep,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRequestArgs) Reset() {
	*x = LogRequestArgs{}
	mi := &file_proto_raft_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequestArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequestArgs) ProtoMessage() {}

func (x *LogRequestArgs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequestArgs.ProtoReflect.Descriptor instead.
func (*LogRequestArgs) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{8}
}

func (x *LogRequestArgs) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *LogRequestArgs) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogRequestArgs) GetPrefixLen() int32 {
	if x != nil {
		return x.PrefixLen
	}
	return 0
}

func (x *LogRequestArgs) GetPrefixTerm() int32 {
	if x != nil {
		return x.PrefixTerm
	}
	return 0
}

func (x *LogRequestArgs) GetCommitLength() int32 {
	if x != nil {
		return x.CommitLength
	}
	return 0
}

func (x *LogRequestArgs) GetSuffix() []*LogEntry {
	if x != nil {
		return x.Suffix
	}
	return nil
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	CurrentTerm   int32                  `protobuf:"varint,2,opt,name=currentTerm,proto3" json:"currentTerm,omitempty"`
	Ack           int32                  `protobuf:"varint,3,opt,name=ack,proto3" json:"ack,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_proto_raft_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{9}
}

func (x *LogResponse) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *LogResponse) GetCurrentTerm() int32 {
	if x != nil {
		return x.CurrentTerm
	}
	return 0
}

func (x *LogResponse) GetAck() int32 {
	if x != nil {
		return x.Ack
	}
	return 0
}

func (x *LogResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type InstallSnapshotRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	LeaderTerm        int32                  `protobuf:"varint,1,opt,name=leaderTerm,proto3" json:"leaderTerm,omitempty"`
	LeaderId          int32                  `protobuf:"varint,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	LastIncludedIndex int32                  `protobuf:"varint,3,opt,name=lastIncludedIndex,proto3" json:"lastIncludedIndex,omitempty"`
	LastIncludedTerm  int32                  `protobuf:"varint,4,opt,name=lastIncludedTerm,proto3" json:"lastIncludedTerm,omitempty"`
	Offset            int32                  `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Data              []byte                 `protobuf:"bytes,6,opt,name=data,proto3" json:"data,omitempty"`
	Done              bool                   `protobuf:"varint,7,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *InstallSnapshotRequest) Reset() {
	*x = InstallSnapshotRequest{}
	mi := &file_proto_raft_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotRequest) ProtoMessage() {}

func (x *InstallSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotRequest.ProtoReflect.Descriptor instead.
func (*InstallSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{10}
}

func (x *InstallSnapshotRequest) GetLeaderTerm() int32 {
	if x != nil {
		return x.LeaderTerm
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastIncludedIndex() int32 {
	if x != nil {
		return x.LastIncludedIndex
	}
	return 0
}

func (x *InstallSnapshotRequest) GetLastIncludedTerm() int32 {
	if x != nil {
		return x.LastIncludedTerm
	}
	return 0
}

func (x *InstallSnapshotRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *InstallSnapshotRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *InstallSnapshotRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type InstallSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int32                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallSnapshotResponse) Reset() {
	*x = InstallSnapshotResponse{}
	mi := &file_proto_raft_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallSnapshotResponse) ProtoMessage() {}

func (x *InstallSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallSnapshotResponse.ProtoReflect.Descriptor instead.
func (*InstallSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{11}
}

func (x *InstallSnapshotResponse) GetTerm() int32 {
	if x != nil {
		return x.Term
	}
	return 0
}

// Partition table update message
type PartitionTableUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of partition_id -> node_id
	// Uses repeated for protobuf compatibility
	Assignments   []*PartitionAssignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionTableUpdate) Reset() {
	*x = PartitionTableUpdate{}
	mi := &file_proto_raft_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionTableUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionTableUpdate) ProtoMessage() {}

func (x *PartitionTableUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionTableUpdate.ProtoReflect.Descriptor instead.
func (*PartitionTableUpdate) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{12}
}

func (x *PartitionTableUpdate) GetAssignments() []*PartitionAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *PartitionTableUpdate) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type PartitionAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartitionId   uint32                 `protobuf:"varint,1,opt,name=partition_id,json=partitionId,proto3" json:"partition_id,omitempty"`
	NodeId        int32                  `protobuf:"varint,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionAssignment) Reset() {
	*x = PartitionAssignment{}
	mi := &file_proto_raft_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionAssignment) ProtoMessage() {}

func (x *PartitionAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionAssignment.ProtoReflect.Descriptor instead.
func (*PartitionAssignment) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{13}
}

func (x *PartitionAssignment) GetPartitionId() uint32 {
	if x != nil {
		return x.PartitionId
	}
	return 0
}

func (x *PartitionAssignment) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

// Replication messages (primary → backup synchronous replication)
type ReplicateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           int32                  `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         int32                  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`        // Only for PUT operations
	Operation     string                 `protobuf:"bytes,3,opt,name=operation,proto3" json:"operation,omitempty"` // "PUT" or "DELETE"
	Version       uint64                 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`    // For future ordering/deduplication
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateRequest) Reset() {
	*x = ReplicateRequest{}
	mi := &file_proto_raft_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateRequest) ProtoMessage() {}

func (x *ReplicateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateRequest.ProtoReflect.Descriptor instead.
func (*ReplicateRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{14}
}

func (x *ReplicateRequest) GetKey() int32 {
	if x != nil {
		return x.Key
	}
	return 0
}

func (x *ReplicateRequest) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ReplicateRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ReplicateRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type ReplicateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // Error message if success = false
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateResponse) Reset() {
	*x = ReplicateResponse{}
	mi := &file_proto_raft_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateResponse) ProtoMessage() {}

func (x *ReplicateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateResponse.ProtoReflect.Descriptor instead.
func (*ReplicateResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{15}
}

func (x *ReplicateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Worker registration messages (Stage 2)
type RegisterWorkerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int32                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	GrpcAddr      string                 `protobuf:"bytes,2,opt,name=grpc_addr,json=grpcAddr,proto3" json:"grpc_addr,omitempty"` // Worker's gRPC address for replication
	HttpAddr      string                 `protobuf:"bytes,3,opt,name=http_addr,json=httpAddr,proto3" json:"http_addr,omitempty"` // Worker's HTTP API address
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkerRequest) Reset() {
	*x = RegisterWorkerRequest{}
	mi := &file_proto_raft_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerRequest) ProtoMessage() {}

func (x *RegisterWorkerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerRequest.ProtoReflect.Descriptor instead.
func (*RegisterWorkerRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterWorkerRequest) GetWorkerId() int32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *RegisterWorkerRequest) GetGrpcAddr() string {
	if x != nil {
		return x.GrpcAddr
	}
	return ""
}

func (x *RegisterWorkerRequest) GetHttpAddr() string {
	if x != nil {
		return x.HttpAddr
	}
	return ""
}

type RegisterWorkerResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                 string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	PartitionTable        *PartitionTable        `protobuf:"bytes,3,opt,name=partition_table,json=partitionTable,proto3" json:"partition_table,omitempty"` // Current partition table
	PartitionTableVersion uint64                 `protobuf:"varint,4,opt,name=partition_table_version,json=partitionTableVersion,proto3" json:"partition_table_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *RegisterWorkerResponse) Reset() {
	*x = RegisterWorkerResponse{}
	mi := &file_proto_raft_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkerResponse) ProtoMessage() {}

func (x *RegisterWorkerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkerResponse.ProtoReflect.Descriptor instead.
func (*RegisterWorkerResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterWorkerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWorkerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterWorkerResponse) GetPartitionTable() *PartitionTable {
	if x != nil {
		return x.PartitionTable
	}
	return nil
}

func (x *RegisterWorkerResponse) GetPartitionTableVersion() uint64 {
	if x != nil {
		return x.PartitionTableVersion
	}
	return 0
}

// Worker heartbeat messages
type WorkerHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      int32                  `protobuf:"varint,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerHeartbeatRequest) Reset() {
	*x = WorkerHeartbeatRequest{}
	mi := &file_proto_raft_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeatRequest) ProtoMessage() {}

func (x *WorkerHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{18}
}

func (x *WorkerHeartbeatRequest) GetWorkerId() int32 {
	if x != nil {
		return x.WorkerId
	}
	return 0
}

func (x *WorkerHeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type WorkerHeartbeatResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Success               bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	PartitionTableVersion uint64                 `protobuf:"varint,2,opt,name=partition_table_version,json=partitionTableVersion,proto3" json:"partition_table_version,omitempty"` // Current partition table version
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *WorkerHeartbeatResponse) Reset() {
	*x = WorkerHeartbeatResponse{}
	mi := &file_proto_raft_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerHeartbeatResponse) ProtoMessage() {}

func (x *WorkerHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*WorkerHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{19}
}

func (x *WorkerHeartbeatResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *WorkerHeartbeatResponse) GetPartitionTableVersion() uint64 {
	if x != nil {
		return x.PartitionTableVersion
	}
	return 0
}

// Partition table update (Raft → Worker)
type UpdatePartitionTableRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PartitionTable *PartitionTable        `protobuf:"bytes,1,opt,name=partition_table,json=partitionTable,proto3" json:"partition_table,omitempty"`
	Version        uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdatePartitionTableRequest) Reset() {
	*x = UpdatePartitionTableRequest{}
	mi := &file_proto_raft_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePartitionTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartitionTableRequest) ProtoMessage() {}

func (x *UpdatePartitionTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartitionTableRequest.ProtoReflect.Descriptor instead.
func (*UpdatePartitionTableRequest) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{20}
}

func (x *UpdatePartitionTableRequest) GetPartitionTable() *PartitionTable {
	if x != nil {
		return x.PartitionTable
	}
	return nil
}

func (x *UpdatePartitionTableRequest) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type UpdatePartitionTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePartitionTableResponse) Reset() {
	*x = UpdatePartitionTableResponse{}
	mi := &file_proto_raft_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePartitionTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePartitionTableResponse) ProtoMessage() {}

func (x *UpdatePartitionTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePartitionTableResponse.ProtoReflect.Descriptor instead.
func (*UpdatePartitionTableResponse) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{21}
}

func (x *UpdatePartitionTableResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Complete partition table structure
type PartitionTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Assignments   []*PartitionAssignment `protobuf:"bytes,1,rep,name=assignments,proto3" json:"assignments,omitempty"`
	Version       uint64                 `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartitionTable) Reset() {
	*x = PartitionTable{}
	mi := &file_proto_raft_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartitionTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartitionTable) ProtoMessage() {}

func (x *PartitionTable) ProtoReflect() protoreflect.Message {
	mi := &file_proto_raft_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartitionTable.ProtoReflect.Descriptor instead.
func (*PartitionTable) Descriptor() ([]byte, []int) {
	return file_proto_raft_proto_rawDescGZIP(), []int{22}
}

func (x *PartitionTable) GetAssignments() []*PartitionAssignment {
	if x != nil {
		return x.Assignments
	}
	return nil
}

func (x *PartitionTable) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

var File_proto_raft_proto protoreflect.FileDescriptor

const file_proto_raft_proto_rawDesc = "" +
	"\n" +
	"\x10proto/raft.proto\x12\x06raftpb\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\"\xcd\x02\n" +
	"\aMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.raftpb.Message.TypeR\x04type\x12\x10\n" +
	"\x03key\x18\x02 \x01(\x05R\x03key\x121\n" +
	"\x05value\x18\x03 \x01(\v2\x1b.google.protobuf.Int32ValueR\x05value\x12+\n" +
	"\x11idempotency_token\x18\x04 \x01(\tR\x10idempotencyToken\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12G\n" +
	"\x10partition_update\x18\x06 \x01(\v2\x1c.raftpb.PartitionTableUpdateR\x0fpartitionUpdate\"@\n" +
	"\x04Type\x12\a\n" +
	"\x03GET\x10\x00\x12\a\n" +
	"\x03PUT\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02\x12\x1a\n" +
	"\x16UPDATE_PARTITION_TABLE\x10\x03\"\x06\n" +
	"\x04Null\"\x1e\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\"K\n" +
	"\vGetResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x14\n" +
	"\x05found\x18\x03 \x01(\bR\x05found\"A\n" +
	"\x0fForwardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\"I\n" +
	"\bLogEntry\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\x12)\n" +
	"\amessage\x18\x02 \x01(\v2\x0f.raftpb.MessageR\amessage\"\xb5\x01\n" +
	"\x0fVoteRequestArgs\x12 \n" +
	"\vcandidateId\x18\x01 \x01(\x05R\vcandidateId\x12$\n" +
	"\rcandidateTerm\x18\x02 \x01(\x05R\rcandidateTerm\x12.\n" +
	"\x12candidateLogLength\x18\x03 \x01(\x05R\x12candidateLogLength\x12*\n" +
	"\x10candidateLogTerm\x18\x04 \x01(\x05R\x10candidateLogTerm\"b\n" +
	"\fVoteResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x05R\x06nodeId\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\x05R\vcurrentTerm\x12\x18\n" +
	"\agranted\x18\x03 \x01(\bR\agranted\"\xcc\x01\n" +
	"\x0eLogRequestArgs\x12\x1a\n" +
	"\bleaderId\x18\x01 \x01(\x05R\bleaderId\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x05R\x04term\x12\x1c\n" +
	"\tprefixLen\x18\x03 \x01(\x05R\tprefixLen\x12\x1e\n" +
	"\n" +
	"prefixTerm\x18\x04 \x01(\x05R\n" +
	"prefixTerm\x12\"\n" +
	"\fcommitLength\x18\x05 \x01(\x05R\fcommitLength\x12(\n" +
	"\x06suffix\x18\x06 \x03(\v2\x10.raftpb.LogEntryR\x06suffix\"s\n" +
	"\vLogResponse\x12\x16\n" +
	"\x06nodeId\x18\x01 \x01(\x05R\x06nodeId\x12 \n" +
	"\vcurrentTerm\x18\x02 \x01(\x05R\vcurrentTerm\x12\x10\n" +
	"\x03ack\x18\x03 \x01(\x05R\x03ack\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\xee\x01\n" +
	"\x16InstallSnapshotRequest\x12\x1e\n" +
	"\n" +
	"leaderTerm\x18\x01 \x01(\x05R\n" +
	"leaderTerm\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\x05R\bleaderId\x12,\n" +
	"\x11lastIncludedIndex\x18\x03 \x01(\x05R\x11lastIncludedIndex\x12*\n" +
	"\x10lastIncludedTerm\x18\x04 \x01(\x05R\x10lastIncludedTerm\x12\x16\n" +
	"\x06offset\x18\x05 \x01(\x05R\x06offset\x12\x12\n" +
	"\x04data\x18\x06 \x01(\fR\x04data\x12\x12\n" +
	"\x04done\x18\a \x01(\bR\x04done\"-\n" +
	"\x17InstallSnapshotResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x05R\x04term\"o\n" +
	"\x14PartitionTableUpdate\x12=\n" +
	"\vassignments\x18\x01 \x03(\v2\x1b.raftpb.PartitionAssignmentR\vassignments\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"Q\n" +
	"\x13PartitionAssignment\x12!\n" +
	"\fpartition_id\x18\x01 \x01(\rR\vpartitionId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\x05R\x06nodeId\"r\n" +
	"\x10ReplicateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value\x12\x1c\n" +
	"\toperation\x18\x03 \x01(\tR\toperation\x12\x18\n" +
	"\aversion\x18\x04 \x01(\x04R\aversion\"C\n" +
	"\x11ReplicateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"n\n" +
	"\x15RegisterWorkerRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x05R\bworkerId\x12\x1b\n" +
	"\tgrpc_addr\x18\x02 \x01(\tR\bgrpcAddr\x12\x1b\n" +
	"\thttp_addr\x18\x03 \x01(\tR\bhttpAddr\"\xc1\x01\n" +
	"\x16RegisterWorkerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12?\n" +
	"\x0fpartition_table\x18\x03 \x01(\v2\x16.raftpb.PartitionTableR\x0epartitionTable\x126\n" +
	"\x17partition_table_version\x18\x04 \x01(\x04R\x15partitionTableVersion\"S\n" +
	"\x16WorkerHeartbeatRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\x05R\bworkerId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"k\n" +
	"\x17WorkerHeartbeatResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x126\n" +
	"\x17partition_table_version\x18\x02 \x01(\x04R\x15partitionTableVersion\"x\n" +
	"\x1bUpdatePartitionTableRequest\x12?\n" +
	"\x0fpartition_table\x18\x01 \x01(\v2\x16.raftpb.PartitionTableR\x0epartitionTable\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion\"8\n" +
	"\x1cUpdatePartitionTableResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"i\n" +
	"\x0ePartitionTable\x12=\n" +
	"\vassignments\x18\x01 \x03(\v2\x1b.raftpb.PartitionAssignmentR\vassignments\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x04R\aversion2\xc6\x05\n" +
	"\x04Raft\x123\n" +
	"\aForward\x12\x0f.raftpb.Message\x1a\x17.raftpb.ForwardResponse\x125\n" +
	"\n" +
	"ForwardGet\x12\x12.raftpb.GetRequest\x1a\x13.raftpb.GetResponse\x12<\n" +
	"\vVoteRequest\x12\x17.raftpb.VoteRequestArgs\x1a\x14.raftpb.VoteResponse\x129\n" +
	"\n" +
	"LogRequest\x12\x16.raftpb.LogRequestArgs\x1a\x13.raftpb.LogResponse\x12;\n" +
	"\tHeartbeat\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x0fInstallSnapshot\x12\x1e.raftpb.InstallSnapshotRequest\x1a\x1f.raftpb.InstallSnapshotResponse\x12@\n" +
	"\tReplicate\x12\x18.raftpb.ReplicateRequest\x1a\x19.raftpb.ReplicateResponse\x12O\n" +
	"\x0eRegisterWorker\x12\x1d.raftpb.RegisterWorkerRequest\x1a\x1e.raftpb.RegisterWorkerResponse\x12R\n" +
	"\x0fWorkerHeartbeat\x12\x1e.raftpb.WorkerHeartbeatRequest\x1a\x1f.raftpb.WorkerHeartbeatResponse\x12a\n" +
	"\x14UpdatePartitionTable\x12#.raftpb.UpdatePartitionTableRequest\x1a$.raftpb.UpdatePartitionTableResponseB\x11Z\x0fpkg/raft/raftpbb\x06proto3"

var (
	file_proto_raft_proto_rawDescOnce sync.Once
	file_proto_raft_proto_rawDescData []byte
)

func file_proto_raft_proto_rawDescGZIP() []byte {
	file_proto_raft_proto_rawDescOnce.Do(func() {
		file_proto_raft_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_raft_proto_rawDesc), len(file_proto_raft_proto_rawDesc)))
	})
	return file_proto_raft_proto_rawDescData
}

var file_proto_raft_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_raft_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_raft_proto_goTypes = []any{
	(Message_Type)(0),                    // 0: raftpb.Message.Type
	(*Message)(nil),                      // 1: raftpb.Message
	(*Null)(nil),                         // 2: raftpb.Null
	(*GetRequest)(nil),                   // 3: raftpb.GetRequest
	(*GetResponse)(nil),                  // 4: raftpb.GetResponse
	(*ForwardResponse)(nil),              // 5: raftpb.ForwardResponse
	(*LogEntry)(nil),                     // 6: raftpb.LogEntry
	(*VoteRequestArgs)(nil),              // 7: raftpb.VoteRequestArgs
	(*VoteResponse)(nil),                 // 8: raftpb.VoteResponse
	(*LogRequestArgs)(nil),               // 9: raftpb.LogRequestArgs
	(*LogResponse)(nil),                  // 10: raftpb.LogResponse
	(*InstallSnapshotRequest)(nil),       // 11: raftpb.InstallSnapshotRequest
	(*InstallSnapshotResponse)(nil),      // 12: raftpb.InstallSnapshotResponse
	(*PartitionTableUpdate)(nil),         // 13: raftpb.PartitionTableUpdate
	(*PartitionAssignment)(nil),          // 14: raftpb.PartitionAssignment
	(*ReplicateRequest)(nil),             // 15: raftpb.ReplicateRequest
	(*ReplicateResponse)(nil),            // 16: raftpb.ReplicateResponse
	(*RegisterWorkerRequest)(nil),        // 17: raftpb.RegisterWorkerRequest
	(*RegisterWorkerResponse)(nil),       // 18: raftpb.RegisterWorkerResponse
	(*WorkerHeartbeatRequest)(nil),       // 19: raftpb.WorkerHeartbeatRequest
	(*WorkerHeartbeatResponse)(nil),      // 20: raftpb.WorkerHeartbeatResponse
	(*UpdatePartitionTableRequest)(nil),  // 21: raftpb.UpdatePartitionTableRequest
	(*UpdatePartitionTableResponse)(nil), // 22: raftpb.UpdatePartitionTableResponse
	(*PartitionTable)(nil),               // 23: raftpb.PartitionTable
	(*wrapperspb.Int32Value)(nil),        // 24: google.protobuf.Int32Value
	(*emptypb.Empty)(nil),                // 25: google.protobuf.Empty
}
var file_proto_raft_proto_depIdxs = []int32{
	0,  // 0: raftpb.Message.type:type_name -> raftpb.Message.Type
	24, // 1: raftpb.Message.value:type_name -> google.protobuf.Int32Value
	13, // 2: raftpb.Message.partition_update:type_name -> raftpb.PartitionTableUpdate
	1,  // 3: raftpb.LogEntry.message:type_name -> raftpb.Message
	6,  // 4: raftpb.LogRequestArgs.suffix:type_name -> raftpb.LogEntry
	14, // 5: raftpb.PartitionTableUpdate.assignments:type_name -> raftpb.PartitionAssignment
	23, // 6: raftpb.RegisterWorkerResponse.partition_table:type_name -> raftpb.PartitionTable
	23, // 7: raftpb.UpdatePartitionTableRequest.partition_table:type_name -> raftpb.PartitionTable
	14, // 8: raftpb.PartitionTable.assignments:type_name -> raftpb.PartitionAssignment
	1,  // 9: raftpb.Raft.Forward:input_type -> raftpb.Message
	3,  // 10: raftpb.Raft.ForwardGet:input_type -> raftpb.GetRequest
	7,  // 11: raftpb.Raft.VoteRequest:input_type -> raftpb.VoteRequestArgs
	9,  // 12: raftpb.Raft.LogRequest:input_type -> raftpb.LogRequestArgs
	25, // 13: raftpb.Raft.Heartbeat:input_type -> google.protobuf.Empty
	11, // 14: raftpb.Raft.InstallSnapshot:input_type -> raftpb.InstallSnapshotRequest
	15, // 15: raftpb.Raft.Replicate:input_type -> raftpb.ReplicateRequest
	17, // 16: raftpb.Raft.RegisterWorker:input_type -> raftpb.RegisterWorkerRequest
	19, // 17: raftpb.Raft.WorkerHeartbeat:input_type -> raftpb.WorkerHeartbeatRequest
	21, // 18: raftpb.Raft.UpdatePartitionTable:input_type -> raftpb.UpdatePartitionTableRequest
	5,  // 19: raftpb.Raft.Forward:output_type -> raftpb.ForwardResponse
	4,  // 20: raftpb.Raft.ForwardGet:output_type -> raftpb.GetResponse
	8,  // 21: raftpb.Raft.VoteRequest:output_type -> raftpb.VoteResponse
	10, // 22: raftpb.Raft.LogRequest:output_type -> raftpb.LogResponse
	25, // 23: raftpb.Raft.Heartbeat:output_type -> google.protobuf.Empty
	12, // 24: raftpb.Raft.InstallSnapshot:output_type -> raftpb.InstallSnapshotResponse
	16, // 25: raftpb.Raft.Replicate:output_type -> raftpb.ReplicateResponse
	18, // 26: raftpb.Raft.RegisterWorker:output_type -> raftpb.RegisterWorkerResponse
	20, // 27: raftpb.Raft.WorkerHeartbeat:output_type -> raftpb.WorkerHeartbeatResponse
	22, // 28: raftpb.Raft.UpdatePartitionTable:output_type -> raftpb.UpdatePartitionTableResponse
	19, // [19:29] is the sub-list for method output_type
	9,  // [9:19] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_raft_proto_init() }
func file_proto_raft_proto_init() {
	if File_proto_raft_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_raft_proto_rawDesc), len(file_proto_raft_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_raft_proto_goTypes,
		DependencyIndexes: file_proto_raft_proto_depIdxs,
		EnumInfos:         file_proto_raft_proto_enumTypes,
		MessageInfos:      file_proto_raft_proto_msgTypes,
	}.Build()
	File_proto_raft_proto = out.File
	file_proto_raft_proto_goTypes = nil
	file_proto_raft_proto_depIdxs = nil
}
